# Generated by Django 3.2.15 on 2022-08-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('setting_name', models.CharField(max_length=50)),
                ('setting_value', models.CharField(max_length=250)),
                ('is_enabled', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
