# Generated by Django 3.2.15 on 2022-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='setting_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
