# Generated by Django 3.2.15 on 2022-08-16 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_applicationsettings_setting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='is_enabled',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1)]),
        ),
    ]
